/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
    '../pragati_national_infrastructure_dashboard.tsx',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-surface': '#2d3133',
        'tertiary-fixed-dim': '#b2c7ef',
        outline: '#74777f',
        'surface-variant': '#e0e3e6',
        'secondary-container': '#fc6018',
        error: '#ba1a1a',
        'on-primary': '#ffffff',
        'on-primary-container': '#778db2',
        'surface-tint': '#495f82',
        'on-primary-fixed': '#001c3b',
        'surface-container-high': '#e6e8eb',
        'on-secondary-container': '#531800',
        background: '#f7f9fc',
        'inverse-on-surface': '#eff1f4',
        'on-secondary-fixed-variant': '#802a00',
        surface: '#f7f9fc',
        'on-secondary': '#ffffff',
        'on-surface': '#191c1e',
        'primary-fixed-dim': '#b1c7f0',
        'error-container': '#ffdad6',
        'inverse-primary': '#b1c7f0',
        'surface-container-highest': '#e0e3e6',
        'primary-fixed': '#d5e3ff',
        'on-error': '#ffffff',
        'primary-container': '#0b2545',
        'surface-container-low': '#f2f4f7',
        'surface-container': '#eceef1',
        'on-surface-variant': '#44474e',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        primary: '#001026',
        secondary: '#a83900',
        tertiary: '#001027',
        'tertiary-container': '#0d2545',
        'on-tertiary-container': '#788db2',
        'on-tertiary-fixed': '#021b3b',
        'on-tertiary-fixed-variant': '#324769',
        'secondary-fixed': '#ffdbcf',
        'secondary-fixed-dim': '#ffb59a',
        'on-secondary-fixed': '#380d00',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        'on-background': '#191c1e',
        'surface-dim': '#d8dadd',
        'surface-bright': '#f7f9fc',
        'primary-fixed-dim': '#b1c7f0',
        'on-primary-fixed-variant': '#314769',
        'tertiary-fixed': '#d6e3ff',
        'outline-variant': '#c4c6cf',
        'inverse-surface': '#2d3133',
      },

      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },

      spacing: {
        margin: '1rem',
        'margin-lg': '2rem',
        'margin-md': '1.5rem',
        gutter: '1rem',
        'gutter-lg': '1.5rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1.25rem',
        'space-xl': '1.75rem',
      },

      fontFamily: {
        'label-md': ['Inter', 'sans-serif'],
        'headline-md': ['Merriweather', 'serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'display-lg': ['Merriweather', 'serif'],
        'display-lg-mobile': ['Merriweather', 'serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'title-md': ['Inter', 'sans-serif'],
        'title-sm': ['Inter', 'sans-serif'],
        'metric-display': ['Inter', 'sans-serif'],
        'headline-lg': ['Merriweather', 'serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },

      fontSize: {
        'label-md': ['0.75rem', {
          lineHeight: '1rem',
          letterSpacing: '0.04em',
          fontWeight: '600',
        }],
        'headline-md': ['1.25rem', {
          lineHeight: '1.75rem',
          fontWeight: '700',
        }],
        'body-md': ['0.875rem', {
          lineHeight: '1.25rem',
          fontWeight: '400',
        }],
        'body-sm': ['0.75rem', {
          lineHeight: '1rem',
          fontWeight: '400',
        }],
        'display-lg': ['2.25rem', {
          lineHeight: '2.75rem',
          letterSpacing: '-0.02em',
          fontWeight: '700',
        }],
        'body-lg': ['1rem', {
          lineHeight: '1.5rem',
          fontWeight: '400',
        }],
        'headline-sm': ['1.125rem', {
          lineHeight: '1.5rem',
          fontWeight: '600',
        }],
        'display-lg-mobile': ['1.75rem', {
          lineHeight: '2.25rem',
          letterSpacing: '-0.01em',
          fontWeight: '700',
        }],
        'title-md': ['1rem', {
          lineHeight: '1.375rem',
          fontWeight: '600',
        }],
        'title-sm': ['0.875rem', {
          lineHeight: '1.25rem',
          fontWeight: '600',
        }],
        'metric-display': ['1.75rem', {
          lineHeight: '2rem',
          letterSpacing: '-0.02em',
          fontWeight: '700',
        }],
        'headline-lg': ['1.5rem', {
          lineHeight: '2rem',
          letterSpacing: '-0.01em',
          fontWeight: '700',
        }],
        'label-sm': ['0.6875rem', {
          lineHeight: '0.875rem',
          letterSpacing: '0.05em',
          fontWeight: '600',
        }],
      },
    },
  },
  plugins: [],
};